name: check

on:
    push:
        branches:
            - master
        tags:
            - v*
    pull_request:
        branches:
            - master

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    version:
        name: Version
        if: startsWith(github.ref_name, 'v')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Check Git tag format
              run: |
                  _tag="${{ github.ref_name }}"
                  if ! printf "%s\n" "$_tag" | grep -q -P '^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(alpha|beta|rc)\.(0|[1-9][0-9]*))?$'; then
                    printf '[ERROR]: Git tag (%s) wrong format\n' "$_tag"
                    exit 1
                  fi

    code:
        name: Code
        needs: version
        if: always() && (needs.version.result == 'success' || needs.version.result == 'skipped')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Python
              uses: actions/setup-python@v4

            - name: Install cmakelang
              run: pip install cmakelang[YAML]

            - name: Check
              run: |
                  chmod u+x ./scripts/check.sh

                  ./scripts/check.sh \
                      --log-level debug

    build:
        name: Build
        needs: code
        if: always() && needs.code.result == 'success'
        strategy:
            fail-fast: true
            matrix:
                # TODO(carlocorradini) Add macos-latest
                os: [ubuntu-latest, windows-latest]
                build: [Debug, Release]
                dis: [5, 6, 7]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install Doxygen
              uses: ssciwr/doxygen-install@v1

            - name: Configure CMake
              run: cmake -S . -B ./build -DCMAKE_BUILD_TYPE:STRING=${{ matrix.build }} -DDIS_VERSION:STRING=${{ matrix.dis }} -DBUILD_SHARED_LIBS:BOOL=OFF -DBUILD_DOCS:BOOL=ON -DBUILD_EXAMPLES:BOOL=ON -DBUILD_TESTS:BOOL=ON

            - name: Build
              run: cmake --build ./build --config ${{ matrix.build }}

            - name: Test
              run: ctest --verbose --test-dir ./build/tests --build-config ${{ matrix.build }}

            # TODO(carlocorradini) Code coverage
