name: release

on:
    workflow_run:
        workflows:
            - check
        types:
            - completed
        branches:
            - master

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        if: github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'refs/tags/v')
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.workflow_run.head_branch }}

            - name: Determine if version is prerelease
              id: prerelease
              env:
                  KDIS_REF_NAME: ${{ github.ref_name }}
              run: |
                  _prerelease=
                  if printf "%s\n" "$KDIS_REF_NAME" | grep -q -P '^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$'; then
                    _prerelease=false
                  else
                    _prerelease=true
                  fi

                  printf 'value=%s\n' "$_prerelease" >> "$GITHUB_OUTPUT"

            # TODO(carlocorradini) Changelog

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  prerelease: ${{ steps.prerelease.outputs.value == 'true' }}
